/*
 * API description for Playlist project
 *
 * This is a sample Playlist Server based on the OpenAPI 3.0 specification.  You can find out more about OpenAPI at [https://oai.github.io/Documentation](https://oai.github.io/Documentation).      Playlist server should provide following functionalities: - Upload item to server - Delete item from server - Get data from one item - Get list of all items on server - Create playlists - Modify playlists - Get a list of all existing playlists Further sources for information   - [Multipart Requests](https://swagger.io/docs/specification/describing-request-body/multipart-requests)   - [Upload And Download Multiple Files Using Web API](https://github.com/JayKrishnareddy/UploadandDownloadFiles)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Wifi.PlaylistEditor.Service.Attributes;
using Wifi.PlaylistEditor.Service.Models;
using Wifi.PlaylistEditor.Service.Domain;
using Wifi.PlaylistEditor.Service.Mappings;
using Wifi.PlaylistEditor.Types;
using Wifi.PlaylistEditor.DbRepositories.MongoDbEntities;

namespace Wifi.PlaylistEditor.Service.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("playlistapi/v1")]
    public class PlaylistsApiController : ControllerBase
    {
        private readonly IPlaylistService _playlistService;
        private readonly IPlaylistFactory _playlistFactory;
        private readonly IPlaylistItemFactory _playlistItemFactory;

        public PlaylistsApiController(IPlaylistService playlistService, IPlaylistFactory playlistFactory, IPlaylistItemFactory playlistItemFactory)
        {
            _playlistService = playlistService;
            _playlistFactory = playlistFactory;
            _playlistItemFactory = playlistItemFactory;
        }

        
        [HttpGet]
        [Route("playlists")]
        [ValidateModelState]        
        public async Task<IActionResult> PlaylistsGet()
        {                                    
            var domainObjects = await _playlistService.GetAllPlaylists();
            if(domainObjects == null)
            {
                return StatusCode(201, new PlaylistList());
            }

            var entity = domainObjects.ToEntity();

            return StatusCode(201, entity);
        }

        [HttpGet]
        [Route("playlists/{playlistId}")]
        [ValidateModelState]
        public async Task<IActionResult> PlaylistsPlaylistIdGet([FromRoute][Required] string playlistId)
        {
            if (string.IsNullOrEmpty(playlistId))
            {
                return StatusCode(400);
            }

            var domainObject = await _playlistService.GetPlaylistById(playlistId);
            if (domainObject == null)
            {
                return StatusCode(404);
            }

            var entity = domainObject.ToEntity();

            return StatusCode(201, entity);
        }

        [HttpDelete]
        [Route("playlists/{playlistId}")]
        [ValidateModelState]        
        public virtual IActionResult PlaylistsPlaylistIdDelete([FromRoute][Required] string playlistId)
        {
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }
        
        [HttpPut]
        [Route("playlists/{playlistId}")]
        [ValidateModelState]     
        public virtual IActionResult PlaylistsPlaylistIdPut([FromBody] PlaylistUpdate body, [FromRoute][Required] string playlistId)
        {
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Playlist));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\n  \"duration\" : 680,\n  \"name\" : \"MyMegaHitsPlaylist_2022\",\n  \"id\" : \"4979875A-A40E-4CC6-99AB-CB5CE62DA97C\",\n  \"items\" : [ {\n    \"duration\" : 205,\n    \"path\" : \"data\\musik\\Bethoven.mp3\",\n    \"thumbnail\" : \"\",\n    \"extension\" : \".mp3\",\n    \"artist\" : \"Gandalf Singer\",\n    \"id\" : \"4979875A-123E-4346-CCAB-CB5CE62DA97C\",\n    \"title\" : \"The bird song\"\n  }, {\n    \"duration\" : 205,\n    \"path\" : \"data\\musik\\Bethoven.mp3\",\n    \"thumbnail\" : \"\",\n    \"extension\" : \".mp3\",\n    \"artist\" : \"Gandalf Singer\",\n    \"id\" : \"4979875A-123E-4346-CCAB-CB5CE62DA97C\",\n    \"title\" : \"The bird song\"\n  } ],\n  \"autor\" : \"DJ Gandalf\",\n  \"dateOfCreation\" : \"2019-05-17T00:00:00.000+00:00\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Playlist>(exampleJson)
            : default(Playlist);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        [HttpPost]
        [Route("playlists")]
        [ValidateModelState]     
        public async Task<IActionResult> PlaylistsPost([FromBody] PlaylistPost entity)
        {            
            if (entity == null)
            {
                return StatusCode(405);
            }

            var domainObject = entity.ToDomain(_playlistFactory);
            foreach (var item in entity.Items)
            {
                var playlistItem = _playlistService.GetItemById(item.Id);
                if (playlistItem != null)
                {
                    domainObject.Add(playlistItem);
                }
                else
                {
                    return StatusCode(404, $"Item with id = {item.Id} not found.");
                }
            }

            _playlistService.AddNewPlaylist(domainObject);

            return StatusCode(201);
        }
    }
}
